# Generated by Django 5.2.12 on 2026-03-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
