# Generated by Django 5.2.12 on 2026-03-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filereader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='primary_language',
        ),
        migrations.CreateModel(
            name='RepositoryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='filereader.repository')),
            ],
        ),
    ]
