# Generated by Django 5.2.12 on 2026-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filereader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='primary_language',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
